-- #######################################################################################
-- HYPRLAND LUA CONFIG
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- hl.config({ autogenerated = true }) -- remove this line to remove the warning

-- This is a Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


----------------
-- CORE LOAD  --
----------------

-- Orchestrator: keep load order explicit for predictable behavior.
local programs = require("core.programs")

require("core.environment").setup()
require("core.visual").setup()
require("core.input").setup()
require("core.monitors").setup()


-------------------
-- PERMISSIONS   --
-------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--     ecosystem = {
--         enforce_permissions = true,
--     },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

require("core.windows").setup()


-------------------
-- KEYBINDINGS   --
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Binds/
require("core.keybinding").setup({
    terminal = programs.terminal,
    fileManager = programs.fileManager,
    menu = programs.menu,
    mainMod = "SUPER", -- Sets "Windows" key as main modifier
})

-----------------
-- AUTOSTART   --
-----------------

require("core.autostart").setup()
